apiVersion: apps/v1
kind: Deployment
metadata:
  name: noti
  labels:
    app: noti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noti
  template:
    metadata:
      labels:
        app: noti
    spec:
      containers:
        - name: noti
          image: username/noti:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5