server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: dashboard
          uri: http://localhost:8081
          predicates:
            - Path=, /fileInfos/**
        - id: drive
          uri: http://localhost:8082
          predicates:
            - Path=/driveFiles/**, 
        - id: indexer
          uri: http://localhost:8083
          predicates:
            - Path=/indices/**, 
        - id: videoprocessing
          uri: http://localhost:8084
          predicates:
            - Path=/videos/**, 
        - id: noti
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, /fileInfos/**
        - id: drive
          uri: http://drive:8080
          predicates:
            - Path=/driveFiles/**, 
        - id: indexer
          uri: http://indexer:8080
          predicates:
            - Path=/indices/**, 
        - id: videoprocessing
          uri: http://videoprocessing:8080
          predicates:
            - Path=/videos/**, 
        - id: noti
          uri: http://noti:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
